"""Offline generator for q4_pencil_coeffs.py (NOT used at runtime).

Derives the CVR038 q4 resultant pencil symbolically in the base-Z canonical
frame (py = 0), exactly divides out the target-independent (1 + t^2)^k and
t^m artifact factors, then emits closed-form coefficient code (sympy CSE) so
the runtime solver needs no sympy.

Run:  python -m wrs.robots.manipulators.denso.cvr038.ik.gen_q4_pencil_coeffs

Background:
    The runtime pencil eliminates s3 from two polynomials that are quadratic
    in s3:
        res_c3(t, s3)        from eliminating m and c3
        res_len_unit(t, s3)  from the q3 length / unit-circle constraint
    Both have coefficients that are polynomials in the rotation invariants
    (px, pz, vx, vy, vz) of the wrist-partition target (py rotated to 0).
    Deflation drops the artifact (1 + t^2) factors that only contribute the
    discarded t = +-i roots, shrinking the pencil from ~deg 32 to deg 12.
"""
import os
import time

import sympy as sp


def _derive():
    t, c3, s3, m = sp.symbols('t c3 s3 m')
    px, pz, vx, vy, vz = sp.symbols('px pz vx vy vz', real=True)
    py = sp.Integer(0)  # base-Z canonical frame

    c4 = (1 - t * t) / (1 + t * t)
    s4 = 2 * t / (1 + t * t)
    a_x = sp.Rational(129, 2000) * s4 - sp.Rational(3, 250)
    a_y = sp.Rational(1, 50) - sp.Rational(129, 2000) * c4
    a_z = sp.Rational(71, 400)
    p23_z = sp.Rational(33, 200)

    rho2 = px * px + py * py
    pos_norm2 = rho2 + pz * pz
    m2 = rho2 - a_y * a_y
    d = pos_norm2 - a_y * a_y

    e_len = sp.together(a_x * a_x + a_z * a_z + p23_z * p23_z + a_y * a_y - pos_norm2
                        + 2 * p23_z * (-s3 * a_x + c3 * a_z)).as_numer_denom()[0]
    e_unit3 = c3 * c3 + s3 * s3 - 1
    e_m = sp.together(m * m - m2).as_numer_denom()[0]
    u = px * vx + py * vy
    vv = py * vx - px * vy
    wx_num = m * u + a_y * vv
    wy_num = -m * vv + a_y * u
    c23_num = m * (a_x - p23_z * s3) + pz * (p23_z * c3 + a_z)
    s23_num = m * (p23_z * c3 + a_z) + pz * (-a_x + p23_z * s3)
    e_wrist = sp.together(-s4 * (c23_num * wx_num - s23_num * vz * rho2)
                          + c4 * wy_num * d).as_numer_denom()[0]

    res_m = sp.resultant(e_wrist, e_m, m)
    res_c3 = sp.Poly(sp.resultant(res_m, e_len, c3), t, s3)
    res_lu = sp.Poly(sp.resultant(e_len, e_unit3, c3), t, s3)

    den = sp.Poly(1 + t * t, t, s3, px, pz, vx, vy, vz)
    tt = sp.Poly(t, t, s3, px, pz, vx, vy, vz)

    def deflate(poly):
        P = sp.Poly(poly, t, s3, px, pz, vx, vy, vz)
        for fac in (den, tt):
            while True:
                q, r = sp.div(P, fac)
                if r.is_zero:
                    P = q
                else:
                    break
        return sp.Poly(P.as_expr(), t, s3)

    return deflate(res_c3), deflate(res_lu), (px, pz, vx, vy, vz)


def _emit(res_c3_d, res_lu_d, argsyms):
    t, s3 = sp.symbols('t s3')
    c3_terms = sp.Poly(res_c3_d.as_expr(), t, s3).terms()
    lu_terms = sp.Poly(res_lu_d.as_expr(), t, s3).terms()
    c3_keys = [k for k, _ in c3_terms]
    lu_keys = [k for k, _ in lu_terms]
    exprs = [co for _, co in c3_terms] + [co for _, co in lu_terms]

    repl, reduced = sp.cse(exprs, optimizations='basic')
    printer = sp.printing.pycode

    lines = []
    lines.append('"""GENERATED by gen_q4_pencil_coeffs.py - do not edit by hand.')
    lines.append('')
    lines.append('Closed-form coefficients of the deflated CVR038 q4 resultant pencil in the')
    lines.append('base-Z canonical frame (py = 0).  res_c3(t, s3) and res_len_unit(t, s3) with')
    lines.append('the (1 + t^2)^k and t^m artifact factors divided out; coefficients are')
    lines.append('polynomials in the rotation invariants (px, pz, vx, vy, vz).')
    lines.append('"""')
    lines.append('')
    lines.append('# (t_power, s3_power) monomial keys, in the same order as eval_coeffs output.')
    lines.append('C3_KEYS = %r' % (tuple(c3_keys),))
    lines.append('LU_KEYS = %r' % (tuple(lu_keys),))
    lines.append('')
    lines.append('')
    lines.append('def eval_coeffs(px, pz, vx, vy, vz):')
    lines.append('    """Return (c3_vals, lu_vals) aligned with C3_KEYS / LU_KEYS."""')
    for sym, sub in repl:
        lines.append('    %s = %s' % (sym, printer(sub)))
    n_c3 = len(c3_keys)
    c3_body = ', '.join(printer(e) for e in reduced[:n_c3])
    lu_body = ', '.join(printer(e) for e in reduced[n_c3:])
    lines.append('    c3_vals = [%s]' % c3_body)
    lines.append('    lu_vals = [%s]' % lu_body)
    lines.append('    return c3_vals, lu_vals')
    lines.append('')
    return '\n'.join(lines)


def main():
    t0 = time.perf_counter()
    print('deriving + deflating (about 45 s)...', flush=True)
    res_c3_d, res_lu_d, argsyms = _derive()
    print('  res_c3 deg_t=%d  res_lu deg_t=%d  (%.1fs)'
          % (res_c3_d.degree(sp.Symbol('t')), res_lu_d.degree(sp.Symbol('t')),
             time.perf_counter() - t0), flush=True)
    src = _emit(res_c3_d, res_lu_d, argsyms)
    out = os.path.join(os.path.dirname(__file__), 'q4_pencil_coeffs.py')
    with open(out, 'w') as f:
        f.write(src)
    print('wrote', out)


if __name__ == '__main__':
    main()
