"""Generate the skill manifest from the catalog in ``wrs/skills.py``.

The catalog holds the domain knowledge (pre/post conditions, failure ->
repair); THIS script grounds it in the source tree -- statically, with ``ast``
like ``gen_api_index.py`` (no imports, no side effects):

  * every ``target`` must resolve to a real function/method, so a rename or
    removal FAILS the build instead of letting the catalog drift;
  * the live signature and first docstring line are attached, so the manifest
    always shows the real API.

Two outputs:

  * ``docs/SKILLS.md``    -- the human page
  * ``docs/skills.json``  -- the machine form (for a task-decomposition layer)

Re-run after editing the catalog or renaming a target:

    py -3.12 tools/gen_skill_manifest.py
"""
import ast
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CATALOG = os.path.join(ROOT, 'wrs', 'skills.py')
MD_OUT = os.path.join(ROOT, 'docs', 'SKILLS.md')
JSON_OUT = os.path.join(ROOT, 'docs', 'skills.json')

KIND_ORDER = ('setup', 'motion', 'state', 'query', 'composed')
KIND_TITLES = {
    'setup': 'Setup',
    'motion': 'Motion actions (plan; return MotionData or None)',
    'state': 'State actions (mutate the held state)',
    'query': 'Queries (produce information -- the reasoning layer)',
    'composed': 'Canonical compositions',
}


def _load_catalog():
    """The SKILLS literal, read statically (the catalog imports nothing and
    computes nothing, so ``literal_eval`` is the whole loader)."""
    with open(CATALOG, 'r', encoding='utf-8') as f:
        tree = ast.parse(f.read())
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
                isinstance(t, ast.Name) and t.id == 'SKILLS'
                for t in node.targets):
            return ast.literal_eval(node.value)
    raise SystemExit(f'{CATALOG}: no SKILLS literal found')


def _resolve_target(target):
    """``target`` -> (signature, first_doc_line), or raise: the dotted path is
    split into the longest existing module file + the def path inside it."""
    parts = target.split('.')
    for i in range(len(parts), 0, -1):
        path = os.path.join(ROOT, *parts[:i]) + '.py'
        if os.path.isfile(path):
            mod_path, rest = path, parts[i:]
            break
    else:
        raise SystemExit(f'skill target {target!r}: no module file found')
    with open(mod_path, 'r', encoding='utf-8') as f:
        node = ast.parse(f.read())
    for name in rest:
        found = next((n for n in node.body
                      if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef,
                                        ast.ClassDef))
                      and n.name == name), None)
        if found is None:
            raise SystemExit(f'skill target {target!r}: {name!r} not found in '
                             f'{os.path.relpath(mod_path, ROOT)} -- catalog '
                             f'out of date?')
        node = found
    if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
        raise SystemExit(f'skill target {target!r} is not a function')
    doc = ast.get_docstring(node)
    first = doc.strip().splitlines()[0].strip() if doc else ''
    return f'{node.name}({ast.unparse(node.args)})', first


def _render_md(skills):
    lines = ['# `wrs` skill manifest', '',
             'The library\'s manipulation vocabulary for a task-decomposition '
             'layer: atomic actions + the geometric queries that couple them. '
             'Auto-generated by `tools/gen_skill_manifest.py` from the catalog '
             'in `wrs/skills.py` (targets validated against the source); edit '
             'the catalog, then re-run.', '',
             'Failure stages reference the `diag=` channel '
             '(`wrs.motion.core.diagnosis`); a `Recipe` surfaces the failed '
             'step\'s stage as `recipe.failure`.', '']
    by_kind = {}
    for s in skills:
        by_kind.setdefault(s['kind'], []).append(s)
    for kind in KIND_ORDER:
        if kind not in by_kind:
            continue
        lines += [f'## {KIND_TITLES[kind]}', '']
        for s in by_kind[kind]:
            lines.append(f'### `{s["name"]}`')
            lines.append(f'_{s["summary"]}_')
            lines.append('')
            lines.append(f'- target: `{s["target"]}`')
            lines.append(f'- signature: `{s["signature"]}`')
            if s.get('recipe_verb'):
                lines.append(f'- recipe verb: `Recipe.{s["recipe_verb"]}`')
            for p in s['pre']:
                lines.append(f'- pre: {p}')
            for p in s['post']:
                lines.append(f'- post: {p}')
            lines.append(f'- returns: {s["returns"]}')
            for stage, repair in s['failures'].items():
                lines.append(f'- on `{stage}`: {repair}')
            lines.append('')
    return lines


def main():
    skills = []
    for entry in _load_catalog():
        signature, doc = _resolve_target(entry['target'])
        skills.append({**entry, 'signature': signature, 'doc': doc})

    os.makedirs(os.path.dirname(MD_OUT), exist_ok=True)
    with open(MD_OUT, 'w', encoding='utf-8') as f:
        f.write('\n'.join(_render_md(skills)))
    with open(JSON_OUT, 'w', encoding='utf-8') as f:
        json.dump(skills, f, indent=2)
        f.write('\n')

    kinds = {s['kind'] for s in skills}
    print(f'wrote {MD_OUT}')
    print(f'wrote {JSON_OUT}')
    print(f'{len(skills)} skills across {len(kinds)} kinds, all targets '
          f'resolved')


if __name__ == '__main__':
    main()
