"""Generate the API docs of the ``wrs`` package, so an assistant (or a
human) can discover in-house functions instead of reaching for trimesh /
scipy / open3d.

Two outputs, both harvested statically with ``ast`` (no imports), so they
are safe and fast and never trigger hardware/GUI side effects:

  * ``docs/API_INDEX.md``      -- one flat page, every module (good for grep)
  * ``docs/api/<subpkg>.md``   -- one page per top-level subpackage, plus an
                                  ``docs/api/index.md`` overview (good for nav)

Re-run after adding/removing public functions:

    py -3.12 tools/gen_api_index.py
"""
import ast
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PKG = os.path.join(ROOT, 'wrs')
FLAT_OUT = os.path.join(ROOT, 'docs', 'API_INDEX.md')
API_DIR = os.path.join(ROOT, 'docs', 'api')


def _first_doc_line(node):
    doc = ast.get_docstring(node)
    if not doc:
        return ''
    return doc.strip().splitlines()[0].strip()


def _public_methods(cls):
    out = []
    for n in cls.body:
        if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if not n.name.startswith('_') and n.name not in out:
                out.append(n.name)  # dedup property getter/setter pairs
    return out


def _module_entries(path):
    with open(path, 'r', encoding='utf-8') as f:
        src = f.read()
    try:
        tree = ast.parse(src)
    except SyntaxError:
        return None, [], []
    mod_doc = _first_doc_line(tree)
    funcs, classes = [], []
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if node.name.startswith('_'):
                continue
            funcs.append((f'{node.name}({ast.unparse(node.args)})',
                          _first_doc_line(node)))
        elif isinstance(node, ast.ClassDef):
            if node.name.startswith('_'):
                continue
            classes.append((node.name, _first_doc_line(node),
                            _public_methods(node)))
    return mod_doc, funcs, classes


def _collect():
    rows = []
    for dirpath, dirnames, filenames in os.walk(PKG):
        if '__pycache__' in dirpath:
            continue
        dirnames.sort()
        for fn in sorted(filenames):
            if not fn.endswith('.py') or fn == '__init__.py':
                continue
            path = os.path.join(dirpath, fn)
            rel = os.path.relpath(path, ROOT).replace(os.sep, '/')
            mod = rel[:-3].replace('/', '.')
            mod_doc, funcs, classes = _module_entries(path)
            if not funcs and not classes:
                continue
            rows.append((mod, rel, mod_doc, funcs, classes))
    return rows


def _render_modules(rows):
    lines = []
    for mod, rel, mod_doc, funcs, classes in rows:
        lines.append(f'## `{mod}`')
        if mod_doc:
            lines.append(f'_{mod_doc}_')
        lines.append('')
        for name, doc in funcs:
            lines.append(f'- `{name}`' + (f' — {doc}' if doc else ''))
        for cname, cdoc, methods in classes:
            lines.append(f'- **class `{cname}`**' +
                         (f' — {cdoc}' if cdoc else ''))
            if methods:
                lines.append('  - methods: ' +
                             ', '.join(f'`{m}`' for m in methods))
        lines.append('')
    return lines


def _subpkg(mod):
    parts = mod.split('.')
    return parts[1] if len(parts) > 1 else mod


def _write(path, lines):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))


_PREFER = ('Prefer these in-house utilities over trimesh / scipy / open3d / '
           'fcl. Auto-generated by `tools/gen_api_index.py` (static ast scan); '
           're-run after adding functions.')


def main():
    rows = _collect()

    # flat page: everything on one page (search / grep)
    flat = ['# `wrs` API index', '', _PREFER, ''] + _render_modules(rows)
    _write(FLAT_OUT, flat)

    # per-subpackage pages
    groups = {}
    for row in rows:
        groups.setdefault(_subpkg(row[0]), []).append(row)

    overview = ['# API reference', '', _PREFER, '',
                'Browse by subpackage (or see the single-page '
                '[API Index](../API_INDEX.md)):', '']
    for sub in sorted(groups):
        grp = groups[sub]
        nfun = sum(len(r[3]) for r in grp)
        ncls = sum(len(r[4]) for r in grp)
        overview.append(f'- [`wrs.{sub}`]({sub}.md) — {len(grp)} modules, '
                        f'{nfun} functions, {ncls} classes')
        page = [f'# `wrs.{sub}`', '', _PREFER, ''] + _render_modules(grp)
        _write(os.path.join(API_DIR, f'{sub}.md'), page)
    _write(os.path.join(API_DIR, 'index.md'), overview)

    n_funcs = sum(len(r[3]) for r in rows)
    n_classes = sum(len(r[4]) for r in rows)
    print(f'wrote {FLAT_OUT}')
    print(f'wrote {len(groups)} subpackage pages under {API_DIR}/')
    print(f'{len(rows)} modules, {n_funcs} functions, {n_classes} classes')


if __name__ == '__main__':
    main()
